#!/usr/bin/env bash
# install nginx web server and sets a custom header
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
sudo sed -i '63i add_header X-Served-By 884-web-02;' /etc/nginx/nginx.conf
sudo service nginx start
