#!/usr/bin/env bash
# Install nginx load balancer HAProxy
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*

echo "frontend Local_Server
        bind *:80
        mode http
        default_backend web_servers" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "backend web_servers
        mode http
        balance roundrobin
        server 3591-web-01 35.231.53.147  check
        server 3591-web-02 54.234.81.97  check" | sudo tee -a  /etc/haproxy/haproxy.cfg
sudo service haproxy restart
