#!/usr/bin/env bash
# Install nginx load balancer HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
sudo cp /etc/default/haproxy /etc/default/haproxy.bak
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.bak
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy


config="frontend Local_Server
        bind *:80
        mode http
        default_backend web_servers
        backend web_servers
        mode http
        balance roundrobin
        server 3591-web-01  35.231.53.147:80 check
        server 3591-web-02  54.234.81.97:80 check"
echo -e $config | tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy reload
sudo service haproxy restart
