#!/usr/bin/env bash
# Install nginx load balancer HAProxy
cfg="
frontend Local_Server
    bind :80
    mode http
    default_backend web_servers
backend web_servers
    mode http
    balance roundrobin
    server 3591-web-01  35.231.53.147:80 check
    server 3591-web-02  54.234.81.97:80 check
"
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

sudo apt-get -y install haproxy=2.4.\*

sudo echo -e "$config" >> sudo /etc/haproxy/haproxy.cfg

sudo echo -e "\nENABLED=1\n" >> sudo /etc/default/haproxy

sudo service haproxy restart
